# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../forms/aboutdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(500, 275)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/applicationIcon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialog.setWindowIcon(icon)
        AboutDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(AboutDialog)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInfo = QtWidgets.QWidget()
        self.tabInfo.setObjectName("tabInfo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabInfo)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLogo = QtWidgets.QLabel(self.tabInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(":/icons/applicationIcon96"))
        self.labelLogo.setScaledContents(False)
        self.labelLogo.setObjectName("labelLogo")
        self.gridLayout.addWidget(self.labelLogo, 0, 0, 3, 1)
        self.labelName = QtWidgets.QLabel(self.tabInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelName.sizePolicy().hasHeightForWidth())
        self.labelName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.gridLayout.addWidget(self.labelName, 0, 1, 1, 1)
        self.labelVersion = QtWidgets.QLabel(self.tabInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelVersion.sizePolicy().hasHeightForWidth())
        self.labelVersion.setSizePolicy(sizePolicy)
        self.labelVersion.setObjectName("labelVersion")
        self.gridLayout.addWidget(self.labelVersion, 1, 1, 1, 1)
        self.labelKmelDbVersion = QtWidgets.QLabel(self.tabInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelKmelDbVersion.sizePolicy().hasHeightForWidth())
        self.labelKmelDbVersion.setSizePolicy(sizePolicy)
        self.labelKmelDbVersion.setObjectName("labelKmelDbVersion")
        self.gridLayout.addWidget(self.labelKmelDbVersion, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.labelInfo = QtWidgets.QLabel(self.tabInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInfo.sizePolicy().hasHeightForWidth())
        self.labelInfo.setSizePolicy(sizePolicy)
        self.labelInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInfo.setWordWrap(True)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout_3.addWidget(self.labelInfo)
        self.tabWidget.addTab(self.tabInfo, "")
        self.tabLicense = QtWidgets.QWidget()
        self.tabLicense.setObjectName("tabLicense")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabLicense)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.licenseTextEdit = QtWidgets.QPlainTextEdit(self.tabLicense)
        self.licenseTextEdit.setUndoRedoEnabled(False)
        self.licenseTextEdit.setReadOnly(True)
        self.licenseTextEdit.setObjectName("licenseTextEdit")
        self.verticalLayout_2.addWidget(self.licenseTextEdit)
        self.tabWidget.addTab(self.tabLicense, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(AboutDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About Kenwood Database Generator"))
        self.labelName.setText(_translate("AboutDialog", "Kenwood Database Generator"))
        self.labelVersion.setText(_translate("AboutDialog", "Version: "))
        self.labelKmelDbVersion.setText(_translate("AboutDialog", "KMEL DB version: 0.2.1"))
        self.labelInfo.setText(_translate("AboutDialog", "<html><head/><body><p>This application is basically a GUI for the kmel_db utility (<a href=\"https://github.com/chrrrisw/kmel_db\"><span style=\" text-decoration: underline; color:#2980b9;\">https://github.com/chrrrisw/kmel_db</span></a>). Its purpose is to generate a Kenwood DAP database on a selected USB drive for using that drive with Kenwood car audio. The drive must be FAT32 formatted. The source code of the utility can be found on <a href=\"https://github.com/vsvyatski/kmel_db_ui\"><span style=\" text-decoration: underline; color:#2980b9;\">Github</span></a>.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInfo), _translate("AboutDialog", "Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLicense), _translate("AboutDialog", "License"))

import appresources_rc
