# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../forms/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 413)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/applicationIcon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.driveListContainer = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driveListContainer.sizePolicy().hasHeightForWidth())
        self.driveListContainer.setSizePolicy(sizePolicy)
        self.driveListContainer.setMinimumSize(QtCore.QSize(100, 0))
        self.driveListContainer.setObjectName("driveListContainer")
        self.driveListLayout = QtWidgets.QVBoxLayout(self.driveListContainer)
        self.driveListLayout.setContentsMargins(0, 0, 0, 0)
        self.driveListLayout.setObjectName("driveListLayout")
        self.driveListLabel = QtWidgets.QLabel(self.driveListContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driveListLabel.sizePolicy().hasHeightForWidth())
        self.driveListLabel.setSizePolicy(sizePolicy)
        self.driveListLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.driveListLabel.setObjectName("driveListLabel")
        self.driveListLayout.addWidget(self.driveListLabel)
        self.driveList = QtWidgets.QListView(self.driveListContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driveList.sizePolicy().hasHeightForWidth())
        self.driveList.setSizePolicy(sizePolicy)
        self.driveList.setMinimumSize(QtCore.QSize(0, 0))
        self.driveList.setBaseSize(QtCore.QSize(0, 0))
        self.driveList.setObjectName("driveList")
        self.driveListLayout.addWidget(self.driveList)
        self.terminalLogContainer = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalLogContainer.sizePolicy().hasHeightForWidth())
        self.terminalLogContainer.setSizePolicy(sizePolicy)
        self.terminalLogContainer.setMinimumSize(QtCore.QSize(250, 0))
        self.terminalLogContainer.setObjectName("terminalLogContainer")
        self.terminalListLayout = QtWidgets.QVBoxLayout(self.terminalLogContainer)
        self.terminalListLayout.setContentsMargins(0, 0, 0, 0)
        self.terminalListLayout.setSpacing(6)
        self.terminalListLayout.setObjectName("terminalListLayout")
        self.terminalLogLabel = QtWidgets.QLabel(self.terminalLogContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalLogLabel.sizePolicy().hasHeightForWidth())
        self.terminalLogLabel.setSizePolicy(sizePolicy)
        self.terminalLogLabel.setObjectName("terminalLogLabel")
        self.terminalListLayout.addWidget(self.terminalLogLabel)
        self.terminalLogWindow = QtWidgets.QPlainTextEdit(self.terminalLogContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminalLogWindow.sizePolicy().hasHeightForWidth())
        self.terminalLogWindow.setSizePolicy(sizePolicy)
        self.terminalLogWindow.setMinimumSize(QtCore.QSize(250, 0))
        self.terminalLogWindow.setDocumentTitle("")
        self.terminalLogWindow.setUndoRedoEnabled(False)
        self.terminalLogWindow.setReadOnly(True)
        self.terminalLogWindow.setPlainText("")
        self.terminalLogWindow.setObjectName("terminalLogWindow")
        self.terminalListLayout.addWidget(self.terminalLogWindow)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/refresh"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setWhatsThis("")
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/write"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate.setIcon(icon2)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView.setIcon(icon3)
        self.actionView.setObjectName("actionView")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/about"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
        self.toolBar.addAction(self.actionRefresh)
        self.toolBar.addAction(self.actionGenerate)
        self.toolBar.addAction(self.actionView)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout)
        self.driveListLabel.setBuddy(self.driveList)
        self.terminalLogLabel.setBuddy(self.terminalLogWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kenwood Database Generator"))
        self.driveListLabel.setText(_translate("MainWindow", "&USB Drives"))
        self.terminalLogLabel.setText(_translate("MainWindow", "&Terminal Output"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionRefresh.setToolTip(_translate("MainWindow", "Refresh Drive List"))
        self.actionGenerate.setText(_translate("MainWindow", "Generate"))
        self.actionGenerate.setToolTip(_translate("MainWindow", "Write Database to Drive"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.actionView.setToolTip(_translate("MainWindow", "Show Database on Drive"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

import appresources_rc
