post_install() {
    cd /opt/kmeldb-ui

    chmod 755 kenwooddbgen.sh
    sh ./install-venv.sh

    cd -
}

post_remove() {
    if [ -d /opt/kmeldb-ui ]
    then
        # Some files (generated by postinstall, for example) are left.
        # We need to clean the mess.
        rm -r /opt/kmeldb-ui
    fi
}
